web:
  image: simongomez95/locketz
  command: sails lift
  ports:
    - "80:1337"
  links:
    - db
  volumes:
    -  c:/users/yolas/workbench/locketz-backend/:/app

#db:
#  image: postgres
#  volumes:
#    - postgres:/var/lib/postgresql/data
#  environment:
#    - POSTGRES_USER=simo
#    - POSTGRES_PASSWORD=contrasena

db:
  image: mongo
  volumes:
    - mongo:/data/db
