web:
  image: simongomez95/locketz
  #command: bash -c "npm install && nodemon -L --debug=0.0.0.0:5858"
  command: bash -c "npm install && nodemon -L"
  ports:
    - "80:1337"
  links:
    - db
  volumes:
    -  .:/app

#db:
#  image: postgres
#  volumes:
#    - postgres:/var/lib/postgresql/data
#  environment:
#    - POSTGRES_USER=simo
#    - POSTGRES_PASSWORD=contrasena

db:
  image: mongo
  volumes:
    - mongo:/data/db